lesson_c4/app/views/__init__.py
from .start import start_bp
from .fight import fight_bp

__all__ = [
    'start_bp',
    'fight_bp'
]

lesson_c4/app/views/fight.py
from flask import Blueprint, render_template, current_app

from lesson_c4.app.setup import arena
from lesson_c4.app.views.start import heroes

# Define Blueprint
fight_bp = Blueprint('Fight', __name__, url_prefix='/fight')



@fight_bp.route('/')
def fight():
    """Display fight page"""
    arena.STAMINA_RECOVERY_PER_TURN = current_app.config['STAMINA_RECOVERY_PER_TURN']
    arena.start_game(player=heroes['player'],
                     enemy=heroes['enemy'])

    return render_template('fight.html', heroes=heroes)


@fight_bp.route('/hit/')
def hit():
    """Player attacks"""
    if arena.game_on:
        result = arena.player_attack()
        return render_template('fight.html', heroes=heroes, result=result)
    return render_template('fight.html', heroes=heroes, battle_result=arena.battle_result)


@fight_bp.route('/use-skill/')
def use_skill():
    """Player uses special skill"""
    if arena.game_on:
        result = arena.player_use_skill()
        return render_template('fight.html', heroes=heroes, result=result)
    return render_template('fight.html', heroes=heroes, battle_result=arena.battle_result)


@fight_bp.route('/pass-turn/')
def pass_turn():
    """Player passes turn"""
    if arena.game_on:
        result = arena.next_turn()
        return render_template('fight.html', heroes=heroes, result=result)
    return render_template('fight.html', heroes=heroes, battle_result=arena.battle_result)


@fight_bp.route('/end-fight/')
def stop_fight():
    """Stop game and return to start page"""
    return render_template("index.html")

lesson_c4/app/views/start.py
from flask import Blueprint, request, render_template, redirect, url_for

# from assets.unit_classes import unit_classes
from lesson_c4.assets.units import Player, Enemy
from lesson_c4.app.setup import heroes, equipment, unit_classes


# Define Blueprint
start_bp = Blueprint('Start', __name__)


@start_bp.route('/')
def start():
    """Display start page"""
    return render_template('index.html')


@start_bp.route('/choose-hero/', methods=['GET', 'POST'])
def choose_hero():
    """Display player unit configuration form"""

    if request.method == 'GET':
        result = {
            "header": 'Выбор героя для игрока',
            "classes": unit_classes,
            "weapons": equipment.get_weapon_names(),
            "armors": equipment.get_armor_names()
        }

        return render_template('hero_choosing.html', result=result)

    if request.method == 'POST':
        # Get form data
        user_name = request.form.get('name')
        unit_class = unit_classes[request.form.get('unit_class')]
        weapon = equipment.get_weapon(request.form.get('weapon'))
        armor = equipment.get_armor(request.form.get('armor'))

        # Create hero
        player_unit = Player(name=user_name, unit_class=unit_class, weapon=weapon, armor=armor)
        heroes['player'] = player_unit

        return redirect(url_for('Start.choose_enemy'))


@start_bp.route('/choose-enemy/', methods=['GET', 'POST'])
def choose_enemy():
    """Display enemy unit configuration form"""

    if request.method == 'GET':
        result = {
            "header": 'Выбор героя для врага',
            "classes": unit_classes,
            "weapons": equipment.get_weapon_names(),
            "armors": equipment.get_armor_names()
        }

        return render_template('hero_choosing.html', result=result)

    if request.method == 'POST':
        # Get form data
        user_name = request.form.get('name')
        unit_class = unit_classes[request.form.get('unit_class')]
        weapon = equipment.get_weapon(request.form.get('weapon'))
        armor = equipment.get_armor(request.form.get('armor'))

        # Create unit
        enemy_unit = Enemy(name=user_name, unit_class=unit_class, weapon=weapon, armor=armor)
        heroes['enemy'] = enemy_unit

        return redirect(url_for('Fight.fight', _external=True))

lesson_c4/app/templates/fight.html
<!DOCTYPE html >
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Sky Wars</title>
    <meta charset="UTF-8">
  </head>
  <body>
    <main style ="width: 1024px; margin: 0 auto;">
      <div class="container">
        <div class="row align-text-top">
          <div class="col align-self-start">
            <h2>{{ heroes.player.name }}</br>класс: <em>{{ heroes.player.unit_class.name }}</em></h2>
            <p><em>Экипировка:</em></p>
            <hr>
            <p>Оружие: {{ heroes.player.weapon.name }}, урон: {{ heroes.player.weapon.min_damage }} - {{ heroes.player.weapon.max_damage }}</br> Броня:
              {{ heroes.player.armor.name }}, защита: {{ heroes.player.armor.defence }}</p>
            <hr>
            <p><em>Информация:</em></p>
            <hr>
            <p>Очки здоровья: {{ heroes.player.health_points }}/{{ heroes.player.unit_class.max_health }}</br> Очки выносливости:
              {{ heroes.player.stamina_points }}/{{ heroes.player.unit_class.max_stamina }}</p>
          </div>
          <div class="col align-self-center">
            <button type="button" onclick="window.location.href='{{ url_for('Fight.hit') }}'" class="btn btn-success m-2">Нанести удар</button></br>
            <button type="button" onclick="window.location.href='{{ url_for('Fight.use_skill') }}'" class="btn btn-danger m-2">Использовать умение</button></br>
            <button type="button" onclick="window.location.href='{{ url_for('Fight.pass_turn') }}'" class="btn btn-warning m-2">Пропустить ход</button></br>
            <button type="button" onclick="window.location.href='{{ url_for('Fight.stop_fight') }}'" class="btn btn-secondary m-2">Завершить бой</button>
          </div>
          <div class="col align-self-start">
            <h2>{{ heroes.enemy.name }}</br>класс: <em>{{ heroes.enemy.unit_class.name }}</em></h2>
            <p><em>Экипировка:</em></p>
            <hr>
            <p>Оружие: {{ heroes.enemy.weapon.name }}, урон: {{ heroes.enemy.weapon.min_damage }} - {{ heroes.enemy.weapon.max_damage }}</br> Броня:
              {{ heroes.enemy.armor.name }}, защита: {{ heroes.enemy.armor.defence }}</p>
            <hr>
            <p><em>Информация:</em></p>
            <hr>
            <p>Очки здоровья: {{ heroes.enemy.health_points }}/{{ heroes.enemy.unit_class.max_health }}</br> Очки выносливости:
              {{ heroes.enemy.stamina_points }}/{{ heroes.enemy.unit_class.max_stamina }}</p>
          </div>
        </div>
      </div>
      <div class="container">
        <hr>
        <div class="row">
          <div class="col align-content-center">
            <p><em>{{ result }}</em></p>
            <p>{{ battle_result }}</p>
          </div>
        </div>
        <hr>
      </div>
    </main>
  </body>
</html>

lesson_c4/app/templates/hero_choosing.html
<!DOCTYPE html >
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Sky Wars</title>
    <meta charset="UTF-8">
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <main style ="width: 320px; margin: 0 auto;">
      <div class="container">
        <h2>{{ result.header }}</h2>
      <form action="", method="post">
        <div class="form-group">
            <input type="text", name="name" class="form-control" placeholder="Имя героя">
          <hr>
          <select class="custom-select" name="unit_class" required>
             <option value="">Выберите класс</option>
              {% for class in result.classes %}
                  <option value="{{ class }}">{{ class }}</option>
              {% endfor %}
           </select>
          <hr>
            <select class="custom-select" name="weapon" required>
             <option value="">Выберите оружие</option>
              {% for weapon_name in result.weapons %}
                  <option value="{{ weapon_name }}">{{ weapon_name }}</option>
              {% endfor %}
           </select>
          <hr>
          <select class="custom-select" name="armor" required>
             <option value="">Выберите броню</option>
              {% for armor_name in result.armors %}
                  <option value="{{ armor_name }}">{{ armor_name }}</option>
              {% endfor %}
           </select>
          <hr>
          </div>
        <button class="btn btn-success" type="submit">Выбрать героя</button>
       </form>
      </div>
    </main>
  </body>
</html>

lesson_c4/app/templates/index.html
<!DOCTYPE html >
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Sky Wars</title>
    <meta charset="UTF-8">
  </head>
  <body>
    <main style ="width: 320px; margin: 0 auto;">
      <div class="container mx-auto">
        <div class="row">
          <h2>SkyWars</h2>
          <div class="col">
            <p><button type="button" onclick="window.location.href='{{ url_for('Start.choose_hero') }}'" class="btn btn-success m-2">Начать игру</button></p>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>